version: '3.4'

services:

  tiendaservicios.api.autor:
    image: ${DOCKER_REGISTRY-}tiendaserviciosapiautor
    container_name: tiendaservicios.api.autor
    build:
      context: .
      dockerfile: TiendaServicios.Api.Autor/Dockerfile
    expose:
      - 53443
    ports:
      - 53443:53443

  tiendaservicios.db.autor:
    image: postgres
    container_name: tiendaservicios.db.autor
    restart: always
    expose:
      - 5433
    ports:
      - 5433:5433
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: tiendaautor
      PGPORT: 5433
    volumes:
      - author-db-data-vol:/var/lib/postgresql/data


  tiendaservicios.api.libro:
    image: ${DOCKER_REGISTRY-}tiendaserviciosapilibro
    container_name: tiendaservicios.api.libro
    build:
      context: .
      dockerfile: TiendaServicios.Api.Libro/Dockerfile
    expose:
      - 53445
    ports:
      - 53445:53445

  tiendaservicios.db.libro:
    image: postgres
    container_name: tiendaservicios.db.libro
    restart: always
    expose:
      - 5434
    ports:
      - 5434:5434
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: tiendalibros
      PGPORT: 5434
    volumes:
      - libro-db-data-vol:/var/lib/postgresql/data


  tiendaservicios.api.carrito:
    image: ${DOCKER_REGISTRY-}tiendaserviciosapicarrito
    container_name: tiendaservicios.api.carrito
    build:
      context: .
      dockerfile: TiendaServicios.Api.Carrito/Dockerfile
    expose:
      - 53447
    ports:
      - 53447:53447

  tiendaservicios.db.carrito:
    image: postgres
    container_name: tiendaservicios.db.carrito
    restart: always
    expose:
      - 5435
    ports:
      - 5435:5435
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: carritocompra
      PGPORT: 5435
    volumes:
      - carrito-db-data-vol:/var/lib/postgresql/data

  tiendaservicios.api.identity:
    image: ${DOCKER_REGISTRY-}tiendaserviciosidentity
    container_name: tiendaservicios.api.identity
    build:
      context: .
      dockerfile: TiendaServicios.Api.Identity/Dockerfile
    expose:
      - 53449
    ports:
      - 53449:53449

  tiendaservicios.db.identity:
    image: postgres
    container_name: tiendaservicios.db.identity
    restart: always
    expose:
      - 5436
    ports:
      - 5436:5436
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: tiendaidentity
      PGPORT: 5436
    volumes:
      - identity-db-data-vol:/var/lib/postgresql/data

  tiendaservicios.api.gateway:
    image: ${DOCKER_REGISTRY-}tiendaserviciosapigateway
    container_name: tiendaservicios.api.gateway
    build:
      context: .
      dockerfile: TiendaServicios.Api.Gateway/Dockerfile
    expose:
      - 53451
    ports:
      - 53451:53451
    #environment:
    #  - ASPNETCORE_ENVIRONMENT=Development
    #  - ASPNETCORE_URL=https://+:53451
    #  - ASPNETCORE_Kestrel__Certificates__Default__Password=tienda-svc
    #  - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/tienda-svc.pfx

volumes:
  author-db-data-vol:
    name: author-db-data-vol
  libro-db-data-vol:
    name: libro-db-data-vol
  carrito-db-data-vol:
    name: carrito-db-data-vol
  identity-db-data-vol:
    name: identity-db-data-vol