// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

namespace TiendaServicios.Api.Autor.Migrations
{
    [DbContext(typeof(ContextoAutor)), Migration("20220609104333_MigracionPostgresInicial")]
    internal class MigracionPostgresInicialBase : MigracionPostgresInicialBaseBase
    {
    }
}